### ISSUE TITLE
Never had wallet.dat or peers.dat in folder (macbook)

### ISSUE THREAD

**Issue by bak5221** [Electra-project/electra-desktop#116]
I am trying to open the wallet but I keep getting 
I never had the old wallet 

A JavaScript error occurred in the main process

Uncaught Exception:
Error: ElectraJs.Wallet: You need to #startDaemon in order to know the wallet #lockState.
at WalletHard.get lockState [as lockState] (/Volumes/Electra Desktop 1.0.8/Electra Desktop.app/Contents/Resources/app.asar/build/main.js:67565:19)
at EventEmitter.electron_1.ipcMain.on (/Volumes/Electra Desktop 1.0.8/Electra Desktop.app/Contents/Resources/app.asar/build/main.js:83515:53)
at emitOne (events.js:115:13)
at EventEmitter.emit (events.js:210:7)
at WebContents.<anonymous> (/Volumes/Electra Desktop 1.0.8/Electra Desktop.app/Contents/Resources/electron.asar/browser/api/web-contents.js:275:13)
at emitTwo (events.js:125:13)
at WebContents.emit (events.js:213:7) "

**Comment by ivangabriele** [comment]
What is you OSX version ?

**Comment by bak5221** [comment]
os x el capitan 10.11.6

**Comment by ivangabriele** [comment]
Ok I close this one as a duplicate.
