### ISSUE TITLE
Error opening Electra Desktop on Ubuntu 16.04

### ISSUE THREAD

**Issue by sandro-csimas** [Electra-project/Electra-Desktop#84]
![image](https://user-images.githubusercontent.com/1282074/38911407-77c2bb56-42a5-11e8-917f-88dd4a88a354.png)
After close the error alert, it shows "Starting daemon" forever.

**Comment by ivangabriele** [comment]
@sandro-csimas It happens when you have the old QT wallet opened at the same time. Can you close all your wallets and try to relaunch only Electra Desktop ?

**Comment by sandro-csimas** [comment]
@ivangabriele, Yes I closed the old QT wallet. Is there any application log to check?

**Comment by sandro-csimas** [comment]
It seems the WalletDaemonState is different of STARTED...
````
  public get lockState(): WalletLockState {
    if (this.LOCK_STATE === undefined && this.DAEMON_STATE !== WalletDaemonState.STARTED) {
      throw new Error(`ElectraJs.Wallet: You need to #startDaemon in order to know the wallet #lockState.`)
    }
    return this.LOCK_STATE as WalletLockState
  }
````

**Comment by sandro-csimas** [comment]
@ivangabriele, I saw few people in Facebook with the same problem. The way to solve it is by removing the Electra directory content (except the wallet.dat) and letting the new wallet creating the content again.

**Comment by bak5221** [comment]
I removed everthing besides wallet.dat. I still get the message.

**Comment by bak5221** [comment]
my error is a little different 

Uncaught Exception:
Error: ElectraJs.Wallet: You need to #startDaemon in order to know the wallet #lockState.
    at WalletHard.get lockState [as lockState] (/Applications/Electra Desktop.app/Contents/Resources/app.asar/build/main.js:67565:19)
    at EventEmitter.electron_1.ipcMain.on (/Applications/Electra Desktop.app/Contents/Resources/app.asar/build/main.js:83515:53)
    at emitOne (events.js:115:13)
    at EventEmitter.emit (events.js:210:7)
    at WebContents.<anonymous> (/Applications/Electra Desktop.app/Contents/Resources/electron.asar/browser/api/web-contents.js:275:13)
    at emitTwo (events.js:125:13)
    at WebContents.emit (events.js:213:7)

**Comment by ivangabriele** [comment]
@sandrocsimas @bak5221

Now we need to establish a 100% reproducible case. On Linux, I think this is related to the manually built QT wallet which, depending on which code it was build from, is incompatible with 

Fyi, [here are the Linux build instruction for the QT wallet](https://drive.google.com/file/d/1KTVTS9TDnuZGESkcLmYFVcBx8NO4lq4T/view?usp=sharing).

**Comment by sandrocsimas** [comment]
@ivangabriele, I reproduced minutes ago with the latest QT wallet (manually built) and the latest Electra Desktop.

**Comment by ivangabriele** [comment]
Yep so I confirm the issue is on Electra core side.

**Comment by bak5221** [comment]
im still get this message

**Comment by ivangabriele** [comment]
@bak5221 Please join the `#user-support` channel on [our Discord](https://discord.gg/tT4zsu3). There is a workaround to fix that.
